name: Deploy

on:
  workflow_run:
    workflows:
      - 'Quality Check'
    branches:
      - main
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the images
        run: docker build -t chatsift/modmail:latest -f ./Dockerfile .

      - name: Push to DockerHub
        run: docker push --all-tags chatsift/modmail
